[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",  # Postgres DB 마이그레이션 관리하기 위해
    "fastapi>=0.142.4",
    "greenlet>=3.5.6",  # SQLAlchemy가 비동기를 사용할 수 있게 하기 위해
    "httpx>=0.28.1",
    "pgvector>=0.5.0",  # Postgres DB에 벡터값을 저장하기 위해
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.15.1",
    "python-multipart>=0.0.32",
    "ruff>=0.16.10",
    "sqlalchemy>=2.1.4",  # ORM
    "uvicorn[standard]>=0.54.0",
]

[tool.ruff]
# 기존엔 80이 대세였지만 최근에는 모니터 가로 길이가 길어져 100, 120을 많이 선호함
line-length = 100

[tool.ruff.lint]
# 코드를 더 깔끔하게 강제하기 위한 린트 규칙 활성화 (선택 사항)
select = ["E", "F", "I", "UP", "B"]
